worker_processes 1;
pid /tmp/nginx.pid;
error_log /dev/stderr warn;
events { worker_connections 256; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    server_tokens off;
    sendfile on;
    client_body_temp_path /tmp/client;
    proxy_temp_path /tmp/proxy;
    fastcgi_temp_path /tmp/fastcgi;
    uwsgi_temp_path /tmp/uwsgi;
    scgi_temp_path /tmp/scgi;
    server {
        listen 8080 default_server;
        absolute_redirect off;
        root /usr/share/nginx/html;
        index index.html;
        add_header Cache-Control "no-cache";
        location = / { return 302 /staticsite/; }
        location = /v1/lab/ { return 302 https://edu-hio-bjornarh-v1.bjornar.dev/phpsite/lab/; }
        location = /staticsite/webutvikling/2018/oblig-1/index.php {
            return 302 /staticsite/webutvikling/2018/oblig-1/index.html;
        }
        location ~ \.php$ { return 404; }
        location / { try_files $uri $uri/ $uri.html =404; }
    }
    server {
        listen 8080;
        server_name edu-hio-bjornarh.bjornar.dev;
        root /usr/share/nginx/html/portal;
        index index.html;
        add_header Cache-Control "no-cache";
        location / { try_files $uri $uri/ =404; }
    }
}
